### ISSUE TITLE
Input Method Related Environment Variables of Fcitx 5 could be also set to 'fcitx'

### ISSUE THREAD

**Issue by WhiredPlanck** [AOSC-Dev/imchooser#3]
According to [fcitx5-diagnose's suggestion](https://github.com/fcitx/fcitx5/blob/c4712b173f7cced6e014e4b1c45e585acdd40ce5/data/fcitx5-diagnose.sh#L1170), one is supposed to set the three related environment variables (i.e. `XMODIFIERS`, `GTK_IM_MODULE` and `QT_IM_MODULE`, see [here](https://fcitx-im.org/wiki/Input_method_related_environment_variables)) to 'fcitx' too. Otherwise it will cause some weird problems on some applications.

**Comment by OriginCode** [comment]
Fixed in 1f52890
